### ISSUE TITLE
Extend log function to variable number of parameters

### ISSUE THREAD

**Issue by steros76** [inorganik/debugout.js#1]
If you are interested I patched log function to get a variable number of arguments.

  this.log = function() {
    // log in real time
    if (self.realTimeLoggingOn) console.log.apply(console,arguments);

```
// record log
var inited=false, i, obj;
for (i=0; i<arguments.length; i++) {
  obj=arguments[i];

  var type = self.determineType(obj);
  if (type != null && self.recordLogs) {
    var addition = self.formatType(type, obj);
    // timestamp, formatted for brevity
    if (self.useTimestamps && !inited) {
      var logTime = new Date();
      self.output += self.formatTimestamp(logTime);
    }
    self.output += (inited ? ', ' : '') + addition;
    inited=true;
  }
}

if (inited) {
  self.output+='\n';
  if (self.autoTrim) self.output = self.trimLog(self.output, self.maxLines);
  // local storage
  if (self.useLocalStorage) {
    var last = new Date();
    var saveObject = {
      startTime: self.startTime,
      log: self.output,
      lastLog: last
    }
    saveObject = JSON.stringify(saveObject);
    window.localStorage.setItem('debugout.js', saveObject);
  }
}

self.depth = 0;
self.parentSizes = [0];
self.currentResult = '';
```

  }

**Comment by inorganik** [comment]
hmm, your function doesn't pass any arguments... but overlooking that - It looks like you loop over the args and log each one right? So instead of 

```js
console.log(this);
console.log(that);
```
You would do
```js
console.log(this, that);
```
Is the idea just to save writing more log statements?

**Comment by steros76** [comment]
This let me create a single entry with more information and correlated variables.

**Comment by inorganik** [comment]
Why don't you just create a pull request? I may not merge... but at least I could see all your code

**Comment by jhulme** [comment]
Allowing the .log function to output multiple parameters would be a useful addition. If it could mimic the same functionality as provided here >> https://developer.mozilla.org/en-US/docs/Web/API/console#Outputting_text_to_the_console

I'm having some trouble getting the steros76 code to function correctly currently.

**Comment by steros76** [comment]
Hi jhulme. I forked the project on https://github.com/steros76/debugout.js. Can you test if you still have problems with my code?

**Comment by inorganik** [comment]
You can now pass multiple args to the log method in v1.0 :tada:
