### ISSUE TITLE
maybe some error in source code

### ISSUE THREAD

**Issue by yamybl** [inorganik/debugout.js#15]
when I logs an array with objects which like this:

`[
    { p: 1, m: function () {} },
    { p: 2, m: function () {} }
]`

I got a output which like this:

[
    {
        p: 1,
        m:     function () {}
[
    {
        p: 1,
        m:     function () {}

    }, 
    {
        P: 2,
        m:     function () {}
[
    {
        p: 1,
        m:     function () {}
[
    {
        p: 1,
        m:     function () {}

    }, 
    {
        P: 2,
        m:     function () {}

    }
]

**Comment by inorganik** [comment]
Should be fixed now in v1.0.
