### ISSUE TITLE
Log save on page refresh?

### ISSUE THREAD

**Issue by petr24** [inorganik/debugout.js#19]
Is there a way to have debugout save current logs on page refresh? 
This way I can log some things on the client, if a page refresh occurs I can still download the log sometime later without missing any of the logs prior to page refresh.

**Comment by inorganik** [comment]
You can enable localStorage and debugout saves logs across sessions:

`self.useLocalStorage = true`;

**Comment by petr24** [comment]
WOW talk about stupid on my part. My bad it's right there in the readme. Thanks!

**Comment by inorganik** [comment]
no worries man

**Comment by petr24** [comment]
@inorganik 

Got things setup, and logging. Very simple btw, nice little library. 
My test case, either I am misunderstanding initialization or doesn't work the way I intended.  

I have a chrome extension, and it does some basic DOM manipulation to specific websites we use for work. When you interact with those DOM elements, I log those events. 
If I log directly i.e `bugout.log(msg)` everything works and logs are saved after page reload.

logger.js
```
var bugout = new debugout();
bugout.useTimestamps   = true;
bugout.useLocalStorage = true;
```

events.js
Click the button 3x
```
$(document).on("click", ".test-btn", function () {
        bugout.log("Test log msg"):
});
```

Then I just call `bugout.getLog()` in the console and got the expected results. 
```
dom_ui_events.js:49 ---- Session started: Tue Jul 16 2019 18:13:53 GMT-0700 (Pacific Daylight Time) ----

[2019-07-16 18:14:00]: Test log msg
[2019-07-16 18:14:01]: Test log msg
[2019-07-16 18:14:01]: Test log msg

---- Log retrieved: Tue Jul 16 2019 18:14:01 GMT-0700 (Pacific Daylight Time) ----
---- Session duration: 00:00:08 ----
```

However if I have an intermediate function, my own logger function that logs to debugout. None of the logs are saved. Any reason this is happening?

```
$(document).on("click", ".test-btn", function () {
        logger("Test log msg"):
});

function logger(msg) {
    bugout.log(msg);
}
```
And then call `bugout.getLog()` all the events are there, except when I reload the page, nothing has been saved. 

Thanks.
