### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xricj** [inorganik/debugout.js#8]
Hello,

I use debugout.js for logging data in the console by following the instructions of usage. But when I run the html file of my project to a browser(google chrome) I get the following error in the console:

![bugouterr](https://cloud.githubusercontent.com/assets/22500994/24497801/e9306794-153c-11e7-940c-a2acb1b7cb89.PNG)

what is the problem?

**Comment by inorganik** [comment]
The issues section for open source repos like this are for bugs in the code, not for helping with basic setup. Please stop opening the same issue. As I already mentioned in #7 you have a linking error. If you run the included index.html file included in the repo, you'll see it works fine. 

This is an issue with _your_ build setup and _your_ script bundling and its not the fault or responsibility of anyone working on debugout to fix it.
