### ISSUE TITLE
Post to server example 

### ISSUE THREAD

**Issue by amgadfahmi** [inorganik/debugout.js#9]
Hi,

Great work here, have a small question as you mentioned

>  Post the log to your server via an ajax request if an error or some other event occurs.

Any examples how this can be achieved !

**Comment by inorganik** [comment]
You use `getLog()` which gives you a string of the log, then you can post it via ajax request. For instance if you're using jquery:

```js
$.post( "some/endpoint.php", { log: debugout.getLog() });
```
